# Generated by Django 4.2.4 on 2023-10-28 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Печать', max_length=100, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, max_length=100, verbose_name='Статус')),
                ('description', models.TextField(default='Описание', max_length=500, verbose_name='Описание')),
                ('price', models.IntegerField(default=1500, verbose_name='Цена')),
                ('image', models.ImageField(default='thematics/default.png', upload_to='thematics', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100, verbose_name='Книга')),
                ('date', models.TimeField(default=datetime.datetime(2023, 10, 28, 21, 0, 44, 993260, tzinfo=datetime.timezone.utc), verbose_name='Время')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 10, 28, 21, 0, 44, 993260, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 10, 28, 21, 0, 44, 993260, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 10, 28, 21, 0, 44, 993260, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('services', models.ManyToManyField(null=True, to='books_app.service', verbose_name='Выставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
